name: Node CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        node-version: 10
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
      env:
        CI: true
